FROM texlive/texlive:latest

RUN tlmgr update --self \
    && tlmgr install \
        xetex \
        latexmk \
        enumitem \
        xifthen \
        biber \
        biblatex \
        environ \
        fontawesome5 \
        logreq \
        roboto \
        sourcesanspro \
        tcolorbox \
        trimspaces \
        ifmtarg \
        tikzfill