name: Copy README to Another Repo

on:
  push:
    branches:
      - main # Adjust this to your branch name
    paths:
      - 'README.md' # Limit trigger to the README file

jobs:
  copy-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy README to Another Repo
        uses: sator-imaging/Copy-to-Another-Repository@v1
        with:
          target-filepath: 'README.md' # File path to copy
          output-branch: 'main' # Branch name in the second repo
          output-repo: 'marcohoucheng/marcohoucheng.github.io' # Second repo (replace with your repo)
          git-token: ${{ secrets.TOKEN_TO_ACCESS_OUTPUT_REPO }} # Set your secret token
